language: php

php:
  - 5.3

before_script:
  - phpenv config-add .travis.ini
  - phpenv rehash

script:
  - find ./ -name '*.php' -exec php -l {} \;
  - phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla .
